### ISSUE TITLE
suggested improvement to the instructions

### ISSUE THREAD

**Issue by jwestgard** [hudmol/container_management#107]
In general the instructions are very well done and easy to follow, but I found one point confusing.  Under "Upgrading from a previous release", the instructions say "Each release of this plugin comes with some database schema changes that need to be applied. To upgrade from a previous release ..." and then explains how to run databse migrations.  

This would seem to imply that the first time you use this plugin, the database migration steps are not necessary, but for us this led to a lot of 'table not found' errors.  Once I ran the migration step (even though we had not previously used this plugin), everything went much more smoothly.  Is there any reason not to make the migration steps a mandatory part of the installation?

**Comment by jambun** [comment]
Hi @jwestgard - thanks for the feedback. You're right, it could be a little clearer. The running the database migration is mandatory for the plugin to work.

Please note that the folks over at ArchivesSpace are working to roll this plugin into the core ArchivesSpace code, so if you're considering using this plugin, you might want to hold off until the next major release of AS, which I think is coming soon, and will have this functionality.

Cheers,
James

**Comment by jwestgard** [comment]
Thanks @jambun, it all makes perfect sense now in retrospect.  Thanks also for the heads-up regarding the next core release. We will likely wait for that before putting these features into production, but we wanted to test in the meantime. Thanks again for your response, and for the plugin!
